name: back-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: 'Create env file'
        run: |
          touch .env
          echo JWT_SECRET_KEY="test" > .env
          cat .env

      - name: Go to back and run tests
        run: cd back && npm i && npm test