name: back-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Go to back and run tests
        run: |
          touch .env
          echo JWT_SECRET_KEY=${JWT_SECRET_KEY} >> .env
          cat .env
          cd back && npm i && npm test
        env: 
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }} 