name: back-tests-workflow

on: pull_request

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Go to back and run tests
        env: 
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }} 
        run: cd back && npm i && npm test
        