name: back-tests-workflow

on: pull_request

jobs:
  test-back:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Go to back and run tests
        run: cd back && npm i && npm test
        env: 
          JWT_SECRET_KEY: "test"
  
  docker:
    needs: test-back
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push back
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:back"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildcarbonback:latest

      - name: Build and push front
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:front"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wildcarbonback:latest